[package]
name = "esp-ota-ble-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
esp-bluedroid = { path = "../esp-bluedroid" }
esp-ota-ble = { path = "../esp-ota-ble" }
